### ISSUE TITLE
About the Prediction

### ISSUE THREAD

**Issue by XiangyanChen** [JiexingQi/tset#1]
Hi! I'm very interested in this work. I pre-trained and fine-tuned this project, and everything ran well. However, when I wanted to infer, I felt confused. I saw a file named "prediction_output.py" and didn't know how to run it. Could you give more explanations or examples on prediction? If I have a natural language query, how do I predict it?

**Comment by shadowbringer1** [comment]
I'm delighted to receive your interest! Apologies for the confusion caused, the file "prediction_output.py" is an unrelated file that was not removed in time. If you wish to predict the SPARQL statement based on a natural language query, you can still do so by running seq2seq/run_seq2seq.py. Simply change the "do_train" parameter in the configuration to false and pass the path of the file you want to predict into the code. This way, you can proceed directly to prediction without training.

**Comment by XiangyanChen** [comment]
Thank you! I've got it.
